services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fmix-web
    ports:
      - "5000:80"
#    depends_on:
#      - mail
    environment:
      - PHP_SENDMAIL_PATH=/usr/sbin/sendmail -S mail:25

# Add mailing support later
#  mail:
#    image: boky/postfix
#    container_name: mail-service
#    environment:
#      - SMTP_SERVER=smtp.gmail.com
#      - SMTP_PORT=587
#      - SMTP_USERNAME=your-email@gmail.com
#      - SMTP_PASSWORD=your-app-password
#      - SMTP_USE_TLS=true
#      - MYNETWORKS=127.0.0.0/8
#      - RELAYHOST=[smtp.gmail.com]:587
#      - MAILNAME=example.com
#    ports:
#      - "25:25"
#    restart: always